# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/ip/dotck_mmcm/dotck_mmcm.xci
# IP: The module: 'dotck_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/dotck_mmcm/dotck_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dotck_mmcm'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/dotck_mmcm/dotck_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'dotck_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/dotck_mmcm/dotck_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dotck_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/ip/dotck_mmcm/dotck_mmcm.xci
# IP: The module: 'dotck_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/dotck_mmcm/dotck_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dotck_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/dotck_mmcm/dotck_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'dotck_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/dotck_mmcm/dotck_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dotck_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
