# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/alexthecat123/LisaFPGA/LisaFPGA.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/alexthecat123/LisaFPGA/LisaFPGA.cache/wt [current_project]
set_property parent.project_path /home/alexthecat123/LisaFPGA/LisaFPGA.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/alexthecat123/LisaFPGA/LisaFPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/fx68k-master/microrom.mem
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/fx68k-master/nanorom.mem
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/ROMs/IOROM_A8.mem
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/ROMs/P6A.mem
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/LisaROMs/CPU_LOW_H.mem
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/LisaROMs/CPU_HIGH_H.mem
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/LisaROMs/CPU_LOW_3A.mem
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/LisaROMs/CPU_HIGH_3A.mem
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/LisaROMs/VSROM_3A.mem
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/LisaROMs/IOROM_40.mem
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/LisaROMs/VSROM_H.mem
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/src/usb_hid_host_rom.mem
}
read_verilog -library xil_defaultlib -sv {
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/AM9512_FPU.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/CPU_board.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/HDMI_Interface.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/IOROM_2732.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/IO_RAM_444C_3.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/IO_board.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/LS323_shiftreg.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/Lite_Adapter.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/MMU_RAM_2148.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/PROM_6309.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/new/SDRAM_Controller_Flat.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/addressable_latch_LS259.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/hdmi/audio_clock_regeneration_packet.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/hdmi/audio_info_frame.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/hdmi/audio_sample_packet.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/hdmi/auxiliary_video_information_info_frame.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/bootrom_2764.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/decoder_2to4.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/decoder_3to8.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/encoder_8to3_LS148.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/fx68k-master/fx68k.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/fx68k-master/fx68kAlu.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/hdmi/hdmi.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/new/mem_board_2mb.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/hdmi/packet_assembler.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/hdmi/packet_picker.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/parity_generator_LS280.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/hdmi/serializer.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/hdmi/source_product_description_info_frame.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/hdmi/tmds_channel.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/fx68k-master/uaddrPla.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/new/usb_keyboard_interface.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/new/usb_mouse_interface.sv
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/top.sv
}
read_verilog -library xil_defaultlib {
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/6502/6502.v
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/6502/ALU.v
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/src/usb_hid_host.v
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/src/usb_hid_host_rom.v
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/lisaStuff/via6522.v
}
read_vhdl -library xil_defaultlib {
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/generic_ram_ena.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_pack-p.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_opt_pack-p.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_alu.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_clkgen.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_reset.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/tb_pack-p.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_pmem_ctrl.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_dmem_ctrl.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_mnemonic_pack-p.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_decoder.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_skip.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_stack.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_io_pack-p.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_io_l.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_io_d.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_io_g.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_io_in.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_sio.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_timer.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_core.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t400_por.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t420_rom.vhd
  /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/imports/t400/t420_notri.vhd
}
read_ip -quiet /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/ip/clock_divider/clock_divider.xci
set_property used_in_implementation false [get_files -all /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/clock_divider/clock_divider_board.xdc]
set_property used_in_implementation false [get_files -all /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/clock_divider/clock_divider.xdc]
set_property used_in_implementation false [get_files -all /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/clock_divider/clock_divider_ooc.xdc]

read_ip -quiet /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/ip/dotck_mmcm/dotck_mmcm.xci
set_property used_in_implementation false [get_files -all /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/dotck_mmcm/dotck_mmcm_board.xdc]
set_property used_in_implementation false [get_files -all /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/dotck_mmcm/dotck_mmcm.xdc]
set_property used_in_implementation false [get_files -all /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/dotck_mmcm/dotck_mmcm_ooc.xdc]

read_ip -quiet /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/sources_1/ip/hdmi_clock_divider/hdmi_clock_divider.xci
set_property used_in_implementation false [get_files -all /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/hdmi_clock_divider/hdmi_clock_divider_board.xdc]
set_property used_in_implementation false [get_files -all /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/hdmi_clock_divider/hdmi_clock_divider.xdc]
set_property used_in_implementation false [get_files -all /home/alexthecat123/LisaFPGA/LisaFPGA.gen/sources_1/ip/hdmi_clock_divider/hdmi_clock_divider_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/constrs_1/imports/lisaStuff/LisaFPGA.xdc
set_property used_in_implementation false [get_files /home/alexthecat123/LisaFPGA/LisaFPGA.srcs/constrs_1/imports/lisaStuff/LisaFPGA.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a100tcsg324-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
